name: StageXL_PopPopWin
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
dependencies:
  bot: '>=0.26.0 <0.27.0'
  browser: '>=0.10.0 <0.11.0'
  stagexl: '>=0.9.0 <0.11.0'
